### ISSUE TITLE
scan.media gets stuck on initial folder

### ISSUE THREAD

**Issue by Tenzinn3** [FourFingerLifeHug/SmokeScreen#1]
When I run `scan.media initialize `

it says the following:

`28.05.2017 19:38:56 INFO: Plex Scan Started...`

However it gets stuck like this and when I run `ps-aux | grep "Plex Media Scanner"` to check what is going on it seems to have gotten stuck on the first folder, it does not ever scan anything else after this. For example:

`localgh+ 22799  0.0  0.2 201124 27964 pts/0    Sl+  19:31   0:00 /usr/lib/plexmediaserver/Plex Media Scanner -s -r -c 1 -d /home/localghost/content/Movies/Catfight (2017)`

Is it meant to take this long or is it just an issue on my end?

**Comment by FourFingerLifeHug** [comment]
The script needs to run as the same user that Plex runs as, otherwise the Plex media scanner doesn't do anything.

**Comment by Tenzinn3** [comment]
Plex runs on the plex user. What would be the best way to do with on cron?

**Comment by FourFingerLifeHug** [comment]
I recommend just running Plex as your user. Edit the /etc/default/plexmediaserver file and put your username in there. Then stop Plex and chown -r the Plex media library folder (/var/lib/plexmediaserver) to your user. Start Plex and it should now be running as your user. 

Optionally, you could run the scripts as the Plex user by editing their crontab and putting them there.

**Comment by Tenzinn3** [comment]
As soon as I have followed those steps for the first option Plex doesn't bring up my library anymore. It's definitely running but I can't connect to it on web. 

For the second option I'd have to modify the scripts as $home for the plex user is not the same as it is for a local user.

`./scan.media: 7: .: Can't open /var/lib/plexmediaserver/.config/SmokeScreen/smokescreen.conf `
